### ISSUE TITLE
Not getting PostBack data from handlePostBack function

### ISSUE THREAD

**Issue by sironronron** [crazymeeks/dragonpay#7]
handlePostback is not retrieving data pass by the PS.

I'm using Laravel 6.* API for my back-end and Nuxtjs for my client-side

`public function dragonpayPaymentPostback()
    {
        $merchant_account = [
            'merchantid' => getenv('DRAGONPAY_MERCHANT_ID'),
            'password'   => getenv('DRAGONPAY_MERCHANT_KEY')
        ];

        $testing = getenv('DRAGONPAY_MERCHANT_SANDBOX');

        $dragonpay = new Dragonpay($merchant_account, $testing);

        $dragonpay->handlePostback(function ($data) {
            // Save Transaction
        });
        
    }`

**Comment by crazymeeks** [comment]
Hi, thanks for raising an issue. In order for me to validate the issue. Please provide the ff:

1. Provide screenshot of application's entry point(route) to handle postback.
2. Can you confirm that your api is successfully called by PS when you make transaction? If yes, please provide log.

**Comment by crazymeeks** [comment]
Hi @sironronron any update on this?

**Comment by crazymeeks** [comment]
Hi @sironronron validated this issue and already fixed!. Please refer to **v3.2.3**. Here's the link to updated version: https://github.com/crazymeeks/dragonpay/wiki/v3.2.3. Note: if you are using Laravel, you need to use api route and not web route because web route requires csrf_token. Closing this issue now.

Thanks for reporting.
